import { GLCode } from './types';

export const GL_CODES: GLCode[] = [
  { code: '6321', category: 'Meats', description: 'Beef, Pork, Lamb, etc.' },
  { code: '6322', category: 'Groceries', description: 'Dry goods, spices, canned items' },
  { code: '6323', category: 'Produce', description: 'Fruits, Vegetables' },
  { code: '6324', category: 'Bakery', description: 'Bread, Pastries, Flour' },
  { code: '6325', category: 'Dairy', description: 'Milk, Cheese, Butter, Eggs' },
  { code: '6326', category: 'Beverages', description: 'Soft drinks, Juice, Water' },
  { code: '6327', category: 'Seafood', description: 'Fish, Shellfish' },
  { code: '6328', category: 'Poultry', description: 'Chicken, Turkey, Duck' },
  { code: '6318', category: 'Ice Cream / Frozen', description: 'Frozen desserts, Ice cream' },
  { code: '6318', category: 'Coffee', description: 'Coffee beans, grounds' },
  { code: '7326', category: 'Expendable Items', description: 'Paper goods, disposables' },
  { code: '7327', category: 'Non-expendable Items', description: 'Smallwares, equipment' },
  { code: '7332', category: 'Chemicals', description: 'Cleaning supplies, detergents' },
  { code: '7171', category: 'Software / Subscription', description: 'SaaS, Monthly services' },
  { code: '7155', category: 'Laundry', description: 'Linens, Uniform cleaning' },
];

// Based on the user's provided Excel data
export const MASTER_PRODUCT_DB = [
  { productNo: "483920", category: "Produce", description: "Roma Tomatoes, fresh", code: "6323" },
  { productNo: "195674", category: "Produce", description: "Iceberg Lettuce", code: "6323" },
  { productNo: "728450", category: "Produce", description: "Yellow Onions 25 lb", code: "6323" },
  { productNo: "560183", category: "Meat/Protein", description: "Chicken Breast, boneless", code: "6321" },
  { productNo: "614972", category: "Meat/Protein", description: "Ground Beef 80/20", code: "6321" },
  { productNo: "309581", category: "Seafood", description: "Tilapia Fillet, frozen", code: "6318" },
  { productNo: "85219", category: "Dairy", description: "Whole Milk 1 gal", code: "6325" },
  { productNo: "402771", category: "Dairy", description: "Cheddar Cheese Shred", code: "6325" },
  { productNo: "917406", category: "Bakery", description: "Burger Buns 4\"", code: "6324" },
  { productNo: "275810", category: "Dry Grocery", description: "Basmati Rice 25 lb", code: "6322" },
  { productNo: "661503", category: "Dry Grocery", description: "Pasta Penne 5 lb", code: "6322" },
  { productNo: "504982", category: "Frozen", description: "French Fries 6/5 lb", code: "6318" },
  { productNo: "883170", category: "Frozen", description: "Mixed Veggies 5 lb", code: "6318" },
  { productNo: "146298", category: "Beverages", description: "Orange Juice 1 gal", code: "6326" },
  { productNo: "734051", category: "Beverages", description: "Soda Assorted 12 oz cans", code: "6326" },
  { productNo: "920615", category: "Condiments/Sauces", description: "Tomato Ketchup 1 gal", code: "6322" },
  { productNo: "118604", category: "Condiments/Sauces", description: "Mayonnaise 1 gal", code: "6322" },
  { productNo: "597310", category: "Spices/Seasoning", description: "Black Pepper 18 oz", code: "6322" },
  { productNo: "240917", category: "Spices/Seasoning", description: "Chili Powder 16 oz", code: "6322" },
  { productNo: "675208", category: "Oils/Shortening", description: "Canola Oil 35 lb", code: "6322" },
  { productNo: "531904", category: "Disposables", description: "Foam/Bagasse Plates 9\"", code: "7327" },
  { productNo: "862415", category: "Disposables", description: "Takeout Containers 3-comp", code: "7327" },
  { productNo: "410296", category: "Disposables", description: "Paper Cups 12 oz", code: "7326" },
  { productNo: "793105", category: "Paper Products", description: "Paper Towels", code: "7326" },
  { productNo: "680247", category: "Cleaning/Chemicals", description: "Dishwashing Liquid 1 gal", code: "7332" },
  { productNo: "225916", category: "Cleaning/Chemicals", description: "Sanitizer (Quat)", code: "7332" },
  { productNo: "905381", category: "Smallwares", description: "Food Gloves (L)", code: "7326" },
  { productNo: "374602", category: "Smallwares", description: "Aluminum Foil Roll", code: "7327" },
  { productNo: "441287", category: "Produce", description: "Cucumbers, fresh", code: "6323" },
  { productNo: "390615", category: "Produce", description: "Lemons 40 ct", code: "6323" },
  { productNo: "560183", category: "Meats", description: "Ground Beef 80/20", code: "6321" }, // Note: Duplicate prod ID but different category in source? Keeping user provided mapping.
  { productNo: "614972", category: "Meats", description: "Beef Sirloin, portioned", code: "6321" },
  { productNo: "702416", category: "Meats", description: "Pork Shoulder, boneless", code: "6321" },
  { productNo: "330951", category: "Meats", description: "Bacon, sliced 10 lb", code: "6321" },
  { productNo: "588104", category: "Meats", description: "Beef Meatballs, cooked", code: "6321" },
  { productNo: "770214", category: "Poultry", description: "Chicken Breast, boneless", code: "6328" },
  { productNo: "681509", category: "Poultry", description: "Chicken Thighs, boneless", code: "6328" },
  { productNo: "946372", category: "Poultry", description: "Whole Chicken, fryer", code: "6328" },
  { productNo: "215907", category: "Poultry", description: "Turkey Breast, deli", code: "6328" },
  { productNo: "504611", category: "Poultry", description: "Chicken Wings, jumbo", code: "6328" },
  { productNo: "420916", category: "Seafood", description: "Shrimp 26/30, peeled", code: "6327" },
  { productNo: "516230", category: "Seafood", description: "Salmon portions 6 oz", code: "6327" },
  { productNo: "804195", category: "Seafood", description: "Crab meat, pasteurized", code: "6327" },
  { productNo: "673108", category: "Seafood", description: "Cod fillet, frozen", code: "6327" },
  { productNo: "175408", category: "Dairy", description: "Butter, salted 1 lb", code: "6325" },
  { productNo: "690321", category: "Dairy", description: "Heavy Cream 1 qt", code: "6325" },
  { productNo: "281734", category: "Dairy", description: "Yogurt, plain 5 lb", code: "6325" },
  { productNo: "602193", category: "Bakery", description: "Sandwich Bread, white", code: "6324" },
  { productNo: "745109", category: "Bakery", description: "Tortillas 10\" flour", code: "6324" },
  { productNo: "118507", category: "Bakery", description: "Croissants, frozen bake", code: "6324" },
  { productNo: "930116", category: "Bakery", description: "Dinner Rolls, 2 oz", code: "6324" },
  { productNo: "540882", category: "Groceries (Dry Storage)", description: "Canned Tomatoes #10", code: "6322" },
  { productNo: "310769", category: "Groceries (Dry Storage)", description: "Black Beans #10", code: "6322" },
  { productNo: "889014", category: "Groceries (Dry Storage)", description: "All-Purpose Flour 50 lb", code: "6322" },
  { productNo: "771605", category: "Frozen / Ice Cream / Coffee", description: "Ice Cream Vanilla 3 gal", code: "6318" },
  { productNo: "229840", category: "Frozen / Ice Cream / Coffee", description: "Frozen Pizza Cheese 12\"", code: "6318" },
  { productNo: "615330", category: "Frozen / Ice Cream / Coffee", description: "Coffee Beans, dark roast 5 lb", code: "6318" },
  { productNo: "981204", category: "Beverages", description: "Bottled Water 16.9 oz", code: "6326" },
  { productNo: "650319", category: "Beverages", description: "Iced Tea Concentrate", code: "7326" }, // Note: 7326 Expendable in list, usually Bev is 6326? Keeping user list (7326 for tea conc could be error in user list or intentional)
  { productNo: "531904", category: "Expendable Items", description: "Napkins, dinner", code: "7326" },
  { productNo: "374602", category: "Non-Expendable Items", description: "Stock Pot 20 qt", code: "7327" },
  { productNo: "680247", category: "Laundry", description: "Laundry Detergent, commercial", code: "7155" }
];
